# Generated by Django 2.2 on 2019-06-17 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from', models.CharField(max_length=50)),
                ('currency_to', models.CharField(max_length=50)),
                ('rate_set', models.DateField(auto_now=True)),
                ('rate_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_Date', models.DateField(auto_now=True)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferApp.Rate')),
            ],
        ),
    ]
