# Generated by Django 2.2 on 2019-06-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferApp', '0003_rate_unitrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='rate',
            field=models.FloatField(default=None),
        ),
    ]
