# Generated by Django 2.2 on 2019-06-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferApp', '0004_auto_20190619_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='rate_description',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
