# Generated by Django 2.2 on 2019-06-24 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transferApp', '0005_rate_rate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency_to',
            field=models.CharField(default='Gourdes', max_length=50),
        ),
    ]
