# Generated by Django 2.2 on 2019-06-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferApp', '0006_auto_20190623_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_origin',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
